development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_dev
  pool: 5
  username: david
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: portfolio_test
  pool: 5
  username: david
  password: 